### ISSUE TITLE
Documentation for `Bacon.d.Age()`

### ISSUE THREAD

**Issue by henningte** [Maarten14C/rbacon#3]
In the documentation for `Bacon.d.Age()` (file `calc.R`), there probably are some typos:

1. l. 67 is: 
  `#' @description Output all depths of a single given MCMC-derived age estimate.`, 
  but should probably be something like: 
  `#' @description Output all MCMC-derived depth estimates for a single age.`  
2. l. 77 is: 
  `#' @return Outputs all MCMC-derived ages for a given depth.`, 
  but should probably be something like: 
  `#' @return Outputs all MCMC-derived depths for a given age.`

**Comment by Maarten14C** [comment]
Thanks, corrected (sorry for the delay)
